
version: 2

models:
    - name: order_line
      description: "Nettoyage order_line"
      columns:
          - name: id_order_line
          - name: id_order
          - name: date_opended
          - name: date_created
          - name: m_quantity
          - name: m_unit_price
          - name: m_unit_price_exc_vat
          - name: m_total_price_inc_vat
          - name: m_total_price_exc_vat
          - name: m_tax_percent
          - name: m_discount_amount
          - name: dim_type
          - name: dim_category
          - name: dim_name
          - name: dim_status
          - name: dim_feature_type
          - name: dim_unit_measure
