version: 2

models:

  - name: order_line
    description: "Ticket par ligne"
    columns:
     ### PK
      - name: id_order_line
        tests :
          - unique
          - not_null                

  - name: payment_data
    description: "Infos de paiement"
    columns:
    #### PK #####
      - name: id_pay
        tests:
          - unique
          - not_null

  - name: order_data
    description: "Infos sur les commandes"
    columns:
    ### PK
     - name: id_order
       tests:
         - unique
         - not_null
